CATEGORIES = ['FOOD', 'SMARTPHONES', 'WATCHES', 'NOTEBOOKS', 'DECORATION',
              'SERVICE', 'BOOKS', 'NATURE', 'CAMERAS']

MONTHS = ['JANUARY', 'FEBRUARY', 'MARCH', 'MAY', 'APRIL', 'JUNE',
          'JULY', 'AUGUST', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER']